global:
  scrape_interval: 5s

scrape_configs:

  - job_name: nginx
    static_configs:
      - targets: ["54.26.0.20:9113"]

  - job_name: apache
    static_configs:
      - targets: ["54.26.0.21:9117"]



